"""Shared API schemas."""

from server.schemas.common import AsyncEntity, Citation, InquiryQuestionOption, ResourceManifestItem
from server.schemas.requests import (
    ConfirmRecommendationRequest,
    CreateCourseRequest,
    InquiryAnswersRequest,
    ProgressData,
    QaMessageRequest,
    QuizGenerateRequest,
    RecommendationRequest,
    SubmitQuizRequest,
    UploadCompleteRequest,
    UploadInitRequest,
)
from server.schemas.responses import (
    ContinueLearningData,
    CourseRecommendationAction,
    CourseRecommendationListData,
    CourseSummary,
    DashboardData,
    HandoutBlock,
    HandoutOutlineData,
    JumpTargetData,
    ParseRunData,
    QaMessageData,
    QuizData,
    RecommendationCard,
    ResourcePlaybackData,
    ReviewTask,
)

__all__ = [
    "AsyncEntity",
    "Citation",
    "ConfirmRecommendationRequest",
    "ContinueLearningData",
    "CourseRecommendationAction",
    "CourseRecommendationListData",
    "CourseSummary",
    "CreateCourseRequest",
    "DashboardData",
    "HandoutBlock",
    "HandoutOutlineData",
    "InquiryAnswersRequest",
    "InquiryQuestionOption",
    "JumpTargetData",
    "ParseRunData",
    "ProgressData",
    "QaMessageData",
    "QaMessageRequest",
    "QuizGenerateRequest",
    "QuizData",
    "RecommendationCard",
    "RecommendationRequest",
    "ResourceManifestItem",
    "ResourcePlaybackData",
    "ReviewTask",
    "SubmitQuizRequest",
    "UploadCompleteRequest",
    "UploadInitRequest",
]
