"""empty message

Revision ID: 17c0fea96cf7
Revises: c7ad333c823e
Create Date: 2026-05-02 00:00:07.209948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '17c0fea96cf7'
down_revision: Union[str, Sequence[str], None] = 'c7ad333c823e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_segments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('segment_key', sa.String(length=255), nullable=False),
    sa.Column('segment_type', sa.String(length=50), nullable=False),
    sa.Column('order_no', sa.Integer(), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=True),
    sa.Column('slide_no', sa.Integer(), nullable=True),
    sa.Column('start_sec', sa.Integer(), nullable=True),
    sa.Column('end_sec', sa.Integer(), nullable=True),
    sa.Column('section_path', sa.JSON(), nullable=True),
    sa.Column('anchor_key', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_segments_segment_key'), 'course_segments', ['segment_key'], unique=True)
    op.create_table('learning_preferences',
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('goal_type', sa.String(length=50), nullable=True),
    sa.Column('self_level', sa.String(length=50), nullable=True),
    sa.Column('preferred_style', sa.String(length=50), nullable=True),
    sa.Column('time_budget_minutes', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.add_column('courses', sa.Column('active_handout_version_id', sa.BigInteger(), nullable=True))
    op.alter_column('courses', 'id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('courses', 'active_handout_version_id')
    op.drop_table('learning_preferences')
    op.drop_index(op.f('ix_course_segments_segment_key'), table_name='course_segments')
    op.drop_table('course_segments')
    # ### end Alembic commands ###