"""add identity to course id

Revision ID: 4dbd5684c6e4
Revises: 1b319cfadeb3
Create Date: 2026-05-01 16:40:45.939929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '4dbd5684c6e4'
down_revision: Union[str, Sequence[str], None] = '1b319cfadeb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None: 
     #删掉默认值
    op.execute(
        "ALTER TABLE courses ALTER COLUMN id DROP DEFAULT"
    )
    #加identity
    op.execute(
        "ALTER TABLE courses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY"
    )
  

def downgrade() -> None:
    op.execute(
        "ALTER TABLE courses ALTER COLUMN id DROP IDENTITY IF EXISTS"
    )
    # ### end Alembic commands ###