"""empty message

Revision ID: c7ad333c823e
Revises: 4dbd5684c6e4
Create Date: 2026-05-01 22:44:59.284699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'c7ad333c823e'
down_revision: Union[str, Sequence[str], None] = '4dbd5684c6e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('async_tasks', sa.Column('parent_task_id', sa.BigInteger(), nullable=True))
    op.add_column('async_tasks', sa.Column('step_code', sa.String(length=50), nullable=True))
    op.add_column('async_tasks', sa.Column('error_code', sa.String(length=100), nullable=True))
    op.add_column('async_tasks', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('async_tasks', sa.Column('finished_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'async_tasks', 'async_tasks', ['parent_task_id'], ['id'])
    # op.alter_column('courses', 'id',
    #            existing_type=sa.BIGINT(),
    #            server_default=None,
    #            existing_nullable=False,
    #            autoincrement=True)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('courses', 'id',
    #            existing_type=sa.BIGINT(),
    #            server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
    #            existing_nullable=False,
    #            autoincrement=True)
    op.drop_constraint(None, 'async_tasks', type_='foreignkey')
    op.drop_column('async_tasks', 'finished_at')
    op.drop_column('async_tasks', 'started_at')
    op.drop_column('async_tasks', 'error_code')
    op.drop_column('async_tasks', 'step_code')
    op.drop_column('async_tasks', 'parent_task_id')
    # ### end Alembic commands ###